### ISSUE TITLE
Imageloader should accept many arguments

### ISSUE THREAD

**Issue by homm** [zont/image-loader#1]
The task was (to be precise, in Russian):

> Функция принимает в качестве аргументов любое кол-во в любой комбинации:
— строки. URL до картинок, которые нужно загрузить.
— объекты HTMLImageElement, в которые загружены картинки,
либо загружаются картинки, либо даже еще не начали загружать картинки
(только что созданные с помощью new Image(), у которых src будет установлен
после вызова функции).

This means: the function should accept any number of arguments, every of which can be a string or HTMLImageElement. Not a array of arguments.

**Comment by zont** [comment]
Ок, я переделаю.
Почему я выбрал такой вариант: это удобно использовать при загрузке списка картинок, если они получены из какого-либо источника (конфига, с сервера).
Пример с массивом:
```javascript
var imagesList = config.get('list');
ImageLoader(list).then(...);
```
Пример с произвольным количеством аргументов требует от пользователя данного API знания особенностей языка выше junior уровня:
```javascript
var imagesList = config.get('list');
ImageLoader.apply(null, list).then(...);
```

**Comment by zont** [comment]
В задании указано:
```
В колбек  передаются все объекты HTMLImageElement с успешно загруженными изображениями.
```
Я использовал интерфейс из стандарта: http://www.ecma-international.org/ecma-262/6.0/#sec-promise-constructor
```
The resolve function that is passed to an executor function accepts a single argument.
```
Соответственно, по стандарту я не могу вернуть много аргументов.
